name: pip_services_sms
version: "1.0.0"
description: SMS Delivery microservice for Pip.Services in Dart. This microservice is intended mostly to send sms to specified recipients.
homepage: https://github.com/pip-services-infrastructure/pip-services-sms-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.5 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_data: ">=1.0.0 <2.0.0"
  pip_services3_mongodb: ">=1.0.2 <2.0.0"
  pip_services3_rpc: ">=1.0.2 <2.0.0"
  pip_services3_grpc: ">=1.0.0 <2.0.0"
  pip_services3_container: ">=1.0.0 <2.0.0"
  http: "^0.12.0"

  aws_sns_api: ^0.0.5
  
  mustache4dart2: ^0.1.0

  angel_framework: ^2.1.1

dev_dependencies:
  test: '>=1.14.2 <2.0.0'
